project:
  type: book
  output-dir: ../docs/white-paper
book:
  title: "Git in Statistical Programming"
  author: 
      - "Kieran Martin"
      - "Alex Assuied"
  date: "5/22/2025"
  chapters:
    - index.qmd
    - state.qmd
    - benefits.qmd
    - Challenges.qmd
    - part: "Recommendations"
      chapters:
        - recommendations.qmd
        - branching-strategies.qmd
    - audittrail.qmd
    - qcintegration.qmd
    - summary.qmd
    - references.qmd
  appendices:
     - tools.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px
      gutter-width: 0.5rem



